[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:neo4j]
command=/usr/bin/neo4j console
autorestart=true
stopsignal=INT
user=neo4j

[program:qdrant]
command=/qdrant/qdrant
autorestart=true
stopsignal=INT

[program:memos]
command=uvicorn memos.api.server_api:app --host 0.0.0.0 --port 8000 --reload
autorestart=true
stopsignal=INT
environment=HF_ENDPOINT="https://hf-mirror.com"
